baseURL = "https://okagenext.jp/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "OKAGE NEXT"
theme = "blowfish"

[params]
  colorScheme = "blowfish"
  defaultAppearance = "light"
  autoSwitchAppearance = false
  showTitle = false
  